services:
  - type: web
    name: render3
    runtime: node
    repo: https://github.com/m-khalil26/Render3
    region: frankfurt 
    buildCommand : npm build
    startCommand: npm start
    plan: free 
    branch: master 
    rootDir: render3
    envVars: 
      -key: DATABASE_URL
       fromDatabase:
          name: my_db2
          property: connectionString
    


databases:
  - name: my_db2
    region: frankfurt
    plan: free
    databaseName: my_db2


