services:
  - type: web
    name: render3
    runtime: node
    repo: https://github.com/m-khalil26/Render3
    region: frankfurt 
    buildcommand : npm build
    startcommand: npm start
    plan: free 
    branch: master 
    rootDir: render3

databases:
  - name: my_db2
    region: frankfurt
    plan: free
    databaseName: my_db2


